name: "publish canary"

on: 
  workflow_dispatch:
    
  schedule: 
    - cron:  '0 0 * * 5'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive
          fetch-depth: 0
    - name: Setup .npmrc file for publish
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: yarn install
    - name: Publish
      run: |
        yarn publish:canary
